location ~ ^(/listen/azuratest_radio|/radio/8000)$ {
    return 302 /player.html;
}

location ~ ^(/listen/azuratest_radio|/radio/8000)/(.*)$ {
    set $do_redirect "";
    
    if ($http_accept ~* "text/html") {
        set $do_redirect "A";
    }

    if ($args ~* "stream=true") {
        set $do_redirect "";
    }

    if ($do_redirect = "A") {
        return 302 /player.html;
    }

    include proxy_params;
    chunked_transfer_encoding off;

    proxy_intercept_errors    on;
    proxy_next_upstream       error timeout invalid_header;
    proxy_redirect            off;
    proxy_set_header          Cookie "";
    proxy_connect_timeout     60;

    proxy_set_header Host $host//listen/azuratest_radio;

    set $args $args&_ic2=1;
    proxy_pass http://127.0.0.1:8000/$2?$args;
}

# Reverse proxy the WebDJ connection.
location ~ ^(/webdj/azuratest_radio|/radio/8005)(/?)(.*)$ {
    include proxy_params;

    proxy_pass http://127.0.0.1:8005/$3;
}

# Reverse proxy the frontend broadcast.
location /hls/azuratest_radio {
    location ~ \.m3u8$ {
        access_log /var/azuracast/stations/azuratest_radio/config/hls.log hls_json;
    }

    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Cache-Control' 'no-cache';

    alias /var/azuracast/stations/azuratest_radio/hls;
    try_files $uri =404;
}
